name: Build and Release

on:
    push:
        tags:
            - "v*.*.*"

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - name: Install dependencies
              run: npm ci
            - name: Build for Linux
              run: npm run build-linux
            - name: Upload Linux Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: linux-build
                  path: dist/chat-it-out.AppImage

    build-windows:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - name: Install dependencies
              run: npm ci
            - name: Build for Windows
              run: npm run build-win
            - name: Upload Windows Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: windows-build
                  path: dist/chat-it-out.exe

    release:
        runs-on: ubuntu-latest
        needs: [build-linux, build-windows] # Depends on both build jobs
        permissions:
            contents: write # Required to create a release and upload assets
        steps:
            - name: Download Linux Artifact
              uses: actions/download-artifact@v4
              with:
                  name: linux-build
                  path: dist/
            - name: Download Windows Artifact
              uses: actions/download-artifact@v4
              with:
                  name: windows-build
                  path: dist/
            - name: Create Release and Upload Assets
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      dist/chat-it-out.AppImage
                      dist/chat-it-out.exe
